param(
  [ValidateSet("all", "full", "sheet-only", "sync-only")]
  [string]$Profile = "all",
  [string]$AppsScriptDir = "apps_script",
  [string]$OutDir = "out/exports",
  [switch]$CopyToClipboard
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$SheetOnlyExcludeFunctions = @(
  "doGet",
  "getWebAppBootstrapData",
  "runWebEligibility",
  "getWebAppClientConfig_",
  "getWebAppAllowedGoogleClientIds_",
  "sanitizeWebPayload_",
  "sanitizeWebAuthPayload_",
  "assertAllowedObjectKeys_",
  "assertAuthorizedWebUser_",
  "verifyGoogleIdToken_",
  "assertDomainUser_",
  "assertWebRateLimit_",
  "sanitizeWebMessage_",
  "listNamedCourseOptions_",
  "sanitizeWebNamedCourses_",
  "sanitizeWebManualElectives_",
  "buildWebAllowedCourseSet_",
  "copyWebDetailsByKey_"
)

$SheetOnlyExcludeConsts = @(
  "WEBAPP_ALLOWED_DOMAIN_SUFFIX",
  "WEBAPP_ALLOWED_DOMAIN",
  "WEBAPP_GOOGLE_CLIENT_ID_PROPERTY",
  "WEBAPP_ALLOWED_GOOGLE_CLIENT_IDS_PROPERTY",
  "WEBAPP_GOOGLE_TOKENINFO_URL",
  "WEBAPP_ID_TOKEN_CACHE_SECONDS",
  "WEBAPP_MAX_ID_TOKEN_LENGTH",
  "WEBAPP_RATE_LIMIT_MIN_INTERVAL_MS",
  "WEBAPP_RATE_LIMIT_WINDOW_SECONDS",
  "WEBAPP_RATE_LIMIT_MAX_PER_WINDOW"
)

function Get-CheckerFiles([string]$dir) {
  $files = @(
    Get-ChildItem -LiteralPath $dir -Filter *.gs -File |
      Where-Object { $_.Name -notmatch '^Sync' }
  )
  if (-not $files -or $files.Count -eq 0) {
    throw "No checker .gs files found in '$dir'."
  }

  return $files | Sort-Object `
    @{ Expression = { if ($_.Name -ieq "Code.gs") { 0 } else { 1 } } }, `
    @{ Expression = { $_.Name } }
}

function Get-SyncFiles([string]$dir) {
  $files = @(
    Get-ChildItem -LiteralPath $dir -Filter *.gs -File |
      Where-Object { $_.Name -match '^Sync' }
  )
  if (-not $files -or $files.Count -eq 0) {
    throw "No sync .gs files found in '$dir'."
  }
  return $files | Sort-Object Name
}

function Join-GsFiles([System.IO.FileInfo[]]$files) {
  $sb = New-Object System.Text.StringBuilder
  foreach ($file in $files) {
    $raw = Get-Content -LiteralPath $file.FullName -Raw
    [void]$sb.AppendLine("// ===== BEGIN FILE: $($file.Name) =====")
    [void]$sb.AppendLine($raw.TrimEnd())
    [void]$sb.AppendLine("// ===== END FILE: $($file.Name) =====")
    [void]$sb.AppendLine("")
  }
  return $sb.ToString().TrimEnd() + "`n"
}

function Remove-TopLevelFunctions([string]$code, [string[]]$functionNames) {
  if ([string]::IsNullOrWhiteSpace($code)) { return $code }
  if (-not $functionNames -or $functionNames.Count -eq 0) { return $code }

  $exclude = @{}
  foreach ($name in $functionNames) {
    $n = [string]$name
    if ($n) { $exclude[$n] = $true }
  }

  $regex = [regex]'(?m)^function\s+([A-Za-z_][A-Za-z0-9_]*)\s*\('
  $matches = $regex.Matches($code)
  if ($matches.Count -eq 0) { return $code }

  $sb = New-Object System.Text.StringBuilder
  $cursor = 0
  for ($i = 0; $i -lt $matches.Count; $i++) {
    $m = $matches[$i]
    $name = $m.Groups[1].Value
    $start = $m.Index
    $nextStart = if ($i -lt $matches.Count - 1) { $matches[$i + 1].Index } else { $code.Length }

    if ($start -gt $cursor) {
      [void]$sb.Append($code.Substring($cursor, $start - $cursor))
    }

    $block = $code.Substring($start, $nextStart - $start)
    if ($exclude.ContainsKey($name)) {
      [void]$sb.AppendLine("// [export] removed web-only function: $name")
    } else {
      [void]$sb.Append($block)
    }
    $cursor = $nextStart
  }

  if ($cursor -lt $code.Length) {
    [void]$sb.Append($code.Substring($cursor))
  }

  return $sb.ToString()
}

function Remove-ConstDeclarations([string]$code, [string[]]$constNames) {
  if ([string]::IsNullOrWhiteSpace($code)) { return $code }
  if (-not $constNames -or $constNames.Count -eq 0) { return $code }

  $updated = $code
  foreach ($constName in $constNames) {
    $escaped = [regex]::Escape([string]$constName)
    $pattern = "(?m)^\s*const\s+$escaped\s*=\s*.*?;\s*(\r?\n)?"
    $updated = [regex]::Replace($updated, $pattern, "")
  }
  return $updated
}

function Normalize-Spacing([string]$code) {
  $normalized = [regex]::Replace($code, "(\r?\n){3,}", "`n`n")
  return $normalized.TrimEnd() + "`n"
}

function Build-Bundle([string]$profileName, [System.IO.FileInfo[]]$files, [string]$code, [string]$generatedAtUtc) {
  $sourceList = ($files | ForEach-Object { $_.Name }) -join ", "
  $header = @(
    "// Generated by tools/export-appsscript-bundles.ps1",
    "// Profile: $profileName",
    "// GeneratedAtUTC: $generatedAtUtc",
    "// Source files: $sourceList",
    ""
  ) -join "`n"
  return $header + $code
}

function Write-Bundle([string]$fileName, [string]$content, [string]$outDir) {
  if (-not (Test-Path -LiteralPath $outDir)) {
    New-Item -ItemType Directory -Path $outDir -Force | Out-Null
  }

  $path = Join-Path $outDir $fileName
  Set-Content -LiteralPath $path -Value $content -Encoding UTF8
  return $path
}

if (-not (Test-Path -LiteralPath $AppsScriptDir)) {
  throw "Apps Script directory not found: $AppsScriptDir"
}

$generatedAtUtc = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
$created = New-Object System.Collections.Generic.List[string]
$lastOutput = $null

if ($Profile -eq "all" -or $Profile -eq "full") {
  $checkerFiles = Get-CheckerFiles -dir $AppsScriptDir
  $fullCode = Join-GsFiles -files $checkerFiles
  $fullBundle = Build-Bundle -profileName "full" -files $checkerFiles -code $fullCode -generatedAtUtc $generatedAtUtc
  $fullPath = Write-Bundle -fileName "Code.bundle.full.gs" -content $fullBundle -outDir $OutDir
  $created.Add($fullPath) | Out-Null
  $lastOutput = $fullPath
}

if ($Profile -eq "all" -or $Profile -eq "sheet-only") {
  $checkerFiles = Get-CheckerFiles -dir $AppsScriptDir
  $sheetCode = Join-GsFiles -files $checkerFiles
  $sheetCode = Remove-TopLevelFunctions -code $sheetCode -functionNames $SheetOnlyExcludeFunctions
  $sheetCode = Remove-ConstDeclarations -code $sheetCode -constNames $SheetOnlyExcludeConsts
  $sheetCode = Normalize-Spacing -code $sheetCode
  $sheetBundle = Build-Bundle -profileName "sheet-only" -files $checkerFiles -code $sheetCode -generatedAtUtc $generatedAtUtc
  $sheetPath = Write-Bundle -fileName "Code.bundle.sheet-only.gs" -content $sheetBundle -outDir $OutDir
  $created.Add($sheetPath) | Out-Null
  $lastOutput = $sheetPath
}

if ($Profile -eq "all" -or $Profile -eq "sync-only") {
  $syncFiles = Get-SyncFiles -dir $AppsScriptDir
  $syncCode = Join-GsFiles -files $syncFiles
  $syncBundle = Build-Bundle -profileName "sync-only" -files $syncFiles -code $syncCode -generatedAtUtc $generatedAtUtc
  $syncPath = Write-Bundle -fileName "Code.bundle.sync-only.gs" -content $syncBundle -outDir $OutDir
  $created.Add($syncPath) | Out-Null
  $lastOutput = $syncPath
}

if ($CopyToClipboard) {
  if (-not $lastOutput) {
    throw "No bundle output was created, cannot copy to clipboard."
  }
  Set-Clipboard -Value (Get-Content -LiteralPath $lastOutput -Raw)
  Write-Host "Copied to clipboard: $lastOutput"
}

Write-Host ""
Write-Host "Export complete."
foreach ($path in $created) {
  Write-Host (" - " + $path)
}
